window.INTELLIGENCE_DATA = {
  meta: {
    version: "v0.2 接管版",
    date: "2026年8月28日",
    dataMode: "历史样例",
    dataNote: "当前内容用于验证个人阅读流程，不代表今日实时情报。正式采集与自动更新尚未接入。",
    automation: "旧云端推送已暂停",
  },
  managerBrief: {
    label: "个人情报摘要",
    verdict: "情报中枢已经有清晰的前台形态，但生产闭环尚未接通；下一阶段应优先让真实简报进入网站，而不是继续堆演示卡片。",
    context: "今天最需要确认的是系统状态：旧云端推送已经暂停，网站成为主要阅览入口；四个频道仍是初期基线，后续可按实际价值扩展、拆分或结束。",
    mustRead: [
      { id: "A", title: "推送入口已收口", detail: "四条旧云端任务已由用户暂停，普通日报不再继续挤入聊天。", tone: "stable" },
      { id: "B", title: "网站仍是演示数据", detail: "现有判断与数字来自迁移历史，只能验证界面，不能作为当日事实。", tone: "warning" },
      { id: "C", title: "正式内容库存尚为空", detail: "情报简报与情报档案已定义规则，但还没有形成持续更新的正式记录。", tone: "risk" },
    ],
    channelStatus: [
      { name: "中国", status: "待接入", note: "优先恢复每日高质量筛选" },
      { name: "世界", status: "待接入", note: "与中国频道同批更新" },
      { name: "AI", status: "有基线", note: "保留经济指数与产业格局追踪" },
      { name: "直销", status: "有基线", note: "历史口径最成熟，待恢复核验" },
    ],
  },
  channels: [
    { id: "china", name: "中国", count: 2, cadence: "计划：每日", state: "待接入", description: "政策、宏观、产业、商业、科技、资本市场与重要社会变化。", focus: "先恢复高质量晨报，控制数量，保留最重要的结构性变化。" },
    { id: "world", name: "世界", count: 2, cadence: "计划：每日", state: "待接入", description: "地缘政治、全球经济、商业科技、资本市场、科学、能源与气候。", focus: "合并重复事件，突出跨市场和跨行业传导。" },
    { id: "ai", name: "AI", count: 2, cadence: "计划：每周", state: "历史基线", description: "模型、Agent、算力、商业化、AI经济与产业格局。", focus: "从产品发布转向能力、成本、分发和经济影响的变化。" },
    { id: "direct", name: "直销", count: 1, cadence: "计划：周一、周五", state: "历史基线", description: "政策监管、企业动作、渠道重构、产品消费与全球信号。", focus: "继续以企业动作为主轴，观察 Creator 化是否进入制度层。" },
  ],
  signals: [
    {
      id: "cn-profit-structure",
      category: "中国",
      status: "confirmed",
      statusLabel: "历史已确认",
      title: "工业利润增长仍在继续，但增量高度集中于电子与高技术制造",
      summary: "总量数据看起来强，结构却提示传统内需相关行业仍弱。下一步要看消费、地产相关制造与汽车利润能否接力。",
      change: "增长仍集中在少数高技术行业，总量改善没有自动转化成广谱复苏。",
      impact: "判断中国需求时需要拆开行业结构，不能只读取总量增速。",
      recommendation: "正式恢复频道后，持续对比高技术制造、消费制造与地产链利润贡献。",
      topics: ["宏观", "产业"],
      evidence: ["国家统计与行业数据应作为正式版主证据", "当前卡片仅保留迁移历史中的判断结构"],
      tracking: "消费与传统制造利润贡献连续改善",
      featured: true,
    },
    {
      id: "global-energy-rates",
      category: "世界",
      status: "judgment",
      statusLabel: "历史判断",
      title: "能源冲击正在重新抬高“更久、更高”的全球利率风险",
      summary: "地缘冲突的影响可能从军事层面传导到能源、通胀与货币政策，企业融资环境随之收紧。",
      change: "风险的重点从单一冲突扩大到能源、通胀和利率的联动。",
      impact: "高杠杆企业、债券和房地产对这一组合更敏感。",
      recommendation: "正式版需同时核验油价、通胀预期和主要央行指引，不能只凭战事新闻推断。",
      topics: ["地缘", "宏观"],
      evidence: ["需重新核验主要央行文件", "需重新核验能源与航运数据"],
      tracking: "能源冲击是否进入核心通胀与央行措辞",
    },
    {
      id: "ai-full-stack",
      category: "AI",
      status: "judgment",
      statusLabel: "历史判断",
      title: "AI竞争的重心正在从模型榜单转向全栈供给能力",
      summary: "芯片、数据中心、低成本推理和产品分发正在成为同一条竞争链，单一模型榜单的重要性下降。",
      change: "竞争单位从模型能力扩展到算力、成本、产品入口和交易闭环。",
      impact: "评估AI公司时需要同时看能力、单位经济性、分发和基础设施约束。",
      recommendation: "周报按模型、Agent、算力、分发与商业化五个层次比较。",
      topics: ["产业格局", "基础设施"],
      evidence: ["企业披露应与独立基准交叉验证", "当前结论来自迁移历史"],
      tracking: "完成真实任务的成本与人工介入是否持续下降",
    },
    {
      id: "direct-creator",
      category: "直销",
      status: "emerging",
      statusLabel: "历史弱信号",
      title: "Distributor → Creator 不再只是个人尝试，开始被公司化",
      summary: "培训、内容工具与角色设计正在同步变化。真正的观察点是激励、合规和客户关系是否随之重构。",
      change: "个人内容尝试开始进入企业培训和工具体系，但制度变化尚未确认。",
      impact: "如果进入激励和客户归属规则，将改变渠道能力与合规边界。",
      recommendation: "继续观察公司制度、培训材料和一线执行，不把营销口号当作完成转型。",
      topics: ["企业", "渠道"],
      evidence: ["需要企业一手制度与培训材料", "需要一线渠道信号交叉验证"],
      tracking: "激励、合规或客户归属出现制度变化",
    },
    {
      id: "cn-compliance-process",
      category: "中国",
      status: "confirmed",
      statusLabel: "历史已确认",
      title: "监管判断正在从资格审查扩展到完整经营过程是否合规",
      summary: "广告、私域传播、个人内容和线上线下经营被放进同一治理视野，个人品牌化需要与公司治理同步。",
      change: "监管关注点由单一资质向完整经营链路延伸。",
      impact: "企业不能把个人账号与私域经营视为治理盲区。",
      recommendation: "正式频道需以监管文件和执法案例为主证据，并标明适用范围。",
      topics: ["政策", "合规"],
      evidence: ["正式版需链接监管原文", "案例结论需区分地区与适用主体"],
      tracking: "跨平台、线上线下一体化执法口径是否稳定",
    },
    {
      id: "ai-work-penetration",
      category: "AI",
      status: "research",
      statusLabel: "历史研究",
      title: "AI已经广泛进入工作，但对典型职业的任务渗透仍然较浅",
      summary: "当前更像职位内部任务包重组，而不是完整职业被替代。下一触发点是端到端委派比例出现拐点。",
      change: "讨论焦点从使用人数转向任务深度、自动化比例和完整工作流委派。",
      impact: "仅看采用率会高估短期替代，也会低估岗位内部的结构变化。",
      recommendation: "持续对照 Google ATLAS、Anthropic Economic Index 与 OpenAI Signals 的方法和指标。",
      topics: ["AI经济", "就业"],
      evidence: ["三套指数需要按新版本重新核验", "方法变化与样本差异必须单独说明"],
      tracking: "端到端工作流委派比例显著上升",
    },
    {
      id: "global-ai-capex",
      category: "世界",
      status: "confirmed",
      statusLabel: "历史披露",
      title: "AI资本开支周期仍在加速，系统性约束也在同步放大",
      summary: "基础设施投资继续上修，但算力集中、能源约束和安全风险正在形成同一组问题。",
      change: "AI从软件产品周期进一步转成资本、能源与供应链共同驱动的基础设施周期。",
      impact: "机会和风险都不再局限于科技公司估值。",
      recommendation: "把资本开支、利用率、能源、融资与实际收入放在一张观察表里。",
      topics: ["科技", "资本开支"],
      evidence: ["正式版需回到公司财报和监管披露", "市场解读应与一手数据分开"],
      tracking: "基础设施投入能否被利用率和收入增长消化",
    },
  ],
  watchlist: [
    { id: "ai-delegation", state: "升温", tone: "rising", title: "AI经济：辅助 → 委派", baseline: "从采用率转向任务深度和完整工作流委派。", change: "历史基线已建立，当前尚未重新核验。", trigger: "端到端工作流占比显著上升", cadence: "每周" },
    { id: "direct-channel", state: "持续", tone: "stable", title: "直销：角色与渠道重构", baseline: "Distributor 向 Creator 迁移仍是弱信号。", change: "等待企业制度层面的证据。", trigger: "激励、合规或客户归属出现制度变化", cadence: "周一、周五" },
    { id: "rates-energy", state: "风险", tone: "risk", title: "全球利率与能源", baseline: "观察地缘冲突向能源、通胀和利率的传导。", change: "当前没有实时核验结果。", trigger: "油价进入核心通胀与央行指引", cadence: "每日" },
  ],
  briefs: [
    { id: "handover", date: "08.28", kind: "记录", title: "情报中枢启用记录", summary: "定位、网站、自动任务、内容库存与持续追踪基线。", state: "已完成", detail: "这是网站启用时的状态记录：旧云端推送已暂停，网站成为个人情报的主要阅读入口。" },
    { id: "direct-history", date: "历史", kind: "直销", title: "直销行业战略情报基线", summary: "宏观传导、企业动作、渠道重构与 Creator 化观察。", state: "迁移记录", detail: "迁移历史保留了成熟的直销情报口径，可作为恢复正式频道时的编辑标准，但其中事实需要重新核验。" },
    { id: "ai-index-history", date: "历史", kind: "AI", title: "AI经济三大指数研究基线", summary: "ATLAS、Anthropic Economic Index 与 OpenAI Signals。", state: "迁移记录", detail: "历史判断是 AI 正从辅助向委派迁移，但尚无充分的宏观就业替代证据。正式更新时必须重新检查新版本与方法变化。" },
  ],
  sourcePolicy: [
    { level: "S", title: "政府、监管与官方统计", use: "政策、执法、宏观与行业硬数据", rule: "优先作为事实底座，保留发布日期和原文链接。" },
    { level: "S", title: "公司与机构一手披露", use: "财报、产品、研究、制度与战略表述", rule: "确认发生了什么，同时识别企业叙事偏向。" },
    { level: "A", title: "主要通讯社与财经媒体", use: "事件核验、跨国信息与背景补充", rule: "重大事项尽量与原始文件或另一独立来源交叉。" },
    { level: "A", title: "论文与研究机构", use: "方法、指标、长期趋势与机制解释", rule: "说明样本、限制和版本变化，不只摘结论。" },
    { level: "B", title: "行业、渠道与平台信号", use: "发现企业动作、渠道变化和新模式", rule: "用于发现问题，不能单独支撑重大结论。" },
    { level: "C", title: "社交与另类弱信号", use: "提前发现异常、情绪与一线变化", rule: "显式标注弱信号，等待一手或多源证据。" },
  ],
}
